#!/usr/bin/php
<?php
chdir(dirname(__FILE__));
error_reporting(E_ALL);
set_time_limit(0);
ob_implicit_flush();
require '../vendor/autoload.php';
require_once './main.php';
use com\github\tncrazvan\catpaw\CatPaw;
use com\github\tncrazvan\catpaw\Event;

$server = new CatPaw([
    "port" => 80,
    "webRoot" => "./public",
    "bindAddress" => "127.0.0.1",
    "events" => [
        "http"=>Event::getHttpEvents(),
        "websocket"=>Event::getWebsocketEvents()
    ],
    "sessionName" => "_SESSION",
    "ramSession" => [
        "allow" => false,
        "size" => "1024M"
    ],
    "compress" => ["deflate"],
    "headers" => [
        "Cache-Control" => "no-store"
    ]
]);
$server->listen();